apiVersion: iam.mini-org.com/v1
kind: Application
metadata:
  name: databricks
  displayName: "Databricks Workspace"
  description: "Data analytics and machine learning platform"
spec:
  type: oidc
  provider: okta
  config:
    clientId: "${DATABRICKS_CLIENT_ID}"
    clientSecret: "${DATABRICKS_CLIENT_SECRET}"
    redirectUri: "https://mini-org.cloud.databricks.com/login/oauth/callback"
    scopes: ["openid", "email", "profile"]
    responseType: "code"
    grantType: "authorization_code"
    tokenEndpoint: "https://mini-org.cloud.databricks.com/oidc/v1/token"
    userInfoEndpoint: "https://mini-org.cloud.databricks.com/oidc/v1/userinfo"
  attributeMapping:
    email: "preferred_username"
    firstName: "given_name"
    lastName: "family_name"
    groups: "groups"
  roleMapping:
    admin:
      databricksGroups:
        - "admins"
        - "workspace-admins"
      permissions:
        - "workspace:admin"
        - "cluster:create"
        - "job:admin"
        - "sql:admin"
    developer:
      databricksGroups:
        - "users"
        - "developers"
      permissions:
        - "workspace:user"
        - "cluster:create"
        - "job:edit"
        - "notebook:edit"
    operator:
      databricksGroups:
        - "analysts"
        - "operators"
      permissions:
        - "workspace:user"
        - "sql:user"
        - "dashboard:view"
    read-only:
      databricksGroups:
        - "viewers"
      permissions:
        - "workspace:view"
        - "dashboard:view"
    emergency:
      databricksGroups:
        - "admins"
        - "emergency-access"
      permissions:
        - "workspace:admin"
        - "cluster:admin"
      requiresApproval: true
  security:
    enforceSSO: true
    sessionTimeout: "12h"
    requireMFA: true
    allowedNetworks:
      - "10.0.0.0/8"
      - "192.168.1.0/24"